use crate::book::OrderBook;
use crate::constants::{MAX_INSTRUMENTS, MAX_TRADES_PER_MATCH};
use crate::instrument::{Instrument, InstrumentRegistry, SOVEREIGNS};
use crate::pool::OrderPool;

/// A trade generated by one instrument's matching engine.
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct Trade {
    pub buyer: u32,
    pub seller: u32,
    pub price: u32,
    pub qty: u32,
    pub instrument_id: u16,
    pub timestamp: u64,
}

/// Single-writer matching engine with one independent CLOB per instrument.
///
/// This PR deliberately does not introduce matcher threads. All books remain
/// owned by one matcher, which preserves deterministic mutation and avoids
/// cross-book synchronization in the hot path. Horizontal sharding can be
/// introduced later by assigning disjoint instrument ranges to matchers.
pub struct MatchingEngine {
    pub pool: OrderPool,
    pub books: Vec<OrderBook>,
    pub instruments: InstrumentRegistry,
    pub trades: [Trade; MAX_TRADES_PER_MATCH],
    pub trade_count: usize,
}

impl MatchingEngine {
    pub fn new() -> Self {
        Self {
            pool: OrderPool::new(),
            books: (0..MAX_INSTRUMENTS).map(|_| OrderBook::new()).collect(),
            instruments: InstrumentRegistry::from_sovereigns(SOVEREIGNS),
            trades: [Trade::default(); MAX_TRADES_PER_MATCH],
            trade_count: 0,
        }
    }

    #[inline(always)]
    pub fn instrument(&self, instrument_id: u16) -> Option<&Instrument> {
        self.instruments.get(instrument_id)
    }

    #[inline(always)]
    pub fn book(&self, instrument_id: u16) -> Option<&OrderBook> {
        self.books.get(instrument_id as usize)
    }

    #[inline(always)]
    pub fn book_mut(&mut self, instrument_id: u16) -> Option<&mut OrderBook> {
        self.books.get_mut(instrument_id as usize)
    }

    #[inline(always)]
    pub fn process_order(&mut self, idx: u32) -> usize {
        self.trade_count = 0;

        let instrument_id = self.pool.data[idx as usize].instrument_id;
        let side = self.pool.data[idx as usize].side;

        // Invalid instrument IDs are rejected before touching any book.
        if !self.instruments.contains(instrument_id) {
            self.pool.deallocate(idx);
            return 0;
        }

        // Preserve the existing binary cancel command for this PR. Cancellation
        // is explicitly routed through the packet's instrument ID, so it cannot
        // accidentally search or mutate another instrument's book.
        if side == 2 {
            let target_order_id = self.pool.data[idx as usize].order_id;
            self.cancel_order(instrument_id, target_order_id);
            self.pool.deallocate(idx);
            return 0;
        }

        // Only normal buy/sell commands are accepted by this layer.
        if side > 1 {
            self.pool.deallocate(idx);
            return 0;
        }

        let book = &mut self.books[instrument_id as usize];
        let pool = &mut self.pool;
        let trades = &mut self.trades;
        let trade_count = &mut self.trade_count;

        if side == 0 {
            Self::match_buy(pool, book, trades, trade_count, instrument_id, idx);
        } else {
            Self::match_sell(pool, book, trades, trade_count, instrument_id, idx);
        }

        if pool.data[idx as usize].remaining > 0 {
            book.insert_limit(idx, pool);
        } else {
            pool.deallocate(idx);
        }

        *trade_count
    }

    /// Cancel an order only in the book identified by `instrument_id`.
    #[inline(always)]
    pub fn cancel_order(&mut self, instrument_id: u16, order_id: u64) -> bool {
        let Some(book) = self.books.get_mut(instrument_id as usize) else {
            return false;
        };
        if !self.instruments.contains(instrument_id) {
            return false;
        }
        book.cancel_order(order_id, &mut self.pool)
    }

    #[inline(always)]
    pub fn remove_order_by_id(&mut self, instrument_id: u16, order_id: u64) -> bool {
        self.cancel_order(instrument_id, order_id)
    }

    #[inline(always)]
    fn match_buy(
        pool: &mut OrderPool,
        book: &mut OrderBook,
        trades: &mut [Trade; MAX_TRADES_PER_MATCH],
        trade_count: &mut usize,
        instrument_id: u16,
        incoming_idx: u32,
    ) {
        let incoming_price = pool.data[incoming_idx as usize].price;

        while pool.data[incoming_idx as usize].remaining > 0 {
            let Some(best_ask) = book.best_ask() else { break };
            if incoming_price < best_ask {
                break;
            }

            let Some(ask_idx) = book.best_ask_head() else { break };
            let ask_price = pool.data[ask_idx as usize].price;
            let ask_remaining = pool.data[ask_idx as usize].remaining;
            let incoming_remaining = pool.data[incoming_idx as usize].remaining;
            let fill_qty = incoming_remaining.min(ask_remaining);

            pool.data[incoming_idx as usize].remaining -= fill_qty;
            pool.data[ask_idx as usize].remaining -= fill_qty;

            if let Some(level) = book.asks.get_mut(&ask_price) {
                level.volume = level.volume.saturating_sub(fill_qty);
            }

            if *trade_count < MAX_TRADES_PER_MATCH {
                trades[*trade_count] = Trade {
                    buyer: pool.data[incoming_idx as usize].account_id,
                    seller: pool.data[ask_idx as usize].account_id,
                    price: ask_price,
                    qty: fill_qty,
                    instrument_id,
                    timestamp: std::time::SystemTime::now()
                        .duration_since(std::time::UNIX_EPOCH)
                        .unwrap_or_default()
                        .as_nanos() as u64,
                };
                *trade_count += 1;
            }

            if pool.data[ask_idx as usize].remaining == 0 {
                book.remove_order(ask_idx, pool);
            }

            // PR 5 removes this semantic limit. For PR 1, keep the existing
            // fixed output buffer behavior but never allow cross-instrument state.
            if *trade_count >= MAX_TRADES_PER_MATCH {
                break;
            }
        }
    }

    #[inline(always)]
    fn match_sell(
        pool: &mut OrderPool,
        book: &mut OrderBook,
        trades: &mut [Trade; MAX_TRADES_PER_MATCH],
        trade_count: &mut usize,
        instrument_id: u16,
        incoming_idx: u32,
    ) {
        let incoming_price = pool.data[incoming_idx as usize].price;

        while pool.data[incoming_idx as usize].remaining > 0 {
            let Some(best_bid) = book.best_bid() else { break };
            if incoming_price > best_bid {
                break;
            }

            let Some(bid_idx) = book.best_bid_head() else { break };
            let bid_price = pool.data[bid_idx as usize].price;
            let bid_remaining = pool.data[bid_idx as usize].remaining;
            let incoming_remaining = pool.data[incoming_idx as usize].remaining;
            let fill_qty = incoming_remaining.min(bid_remaining);

            pool.data[incoming_idx as usize].remaining -= fill_qty;
            pool.data[bid_idx as usize].remaining -= fill_qty;

            if let Some(level) = book.bids.get_mut(&bid_price) {
                level.volume = level.volume.saturating_sub(fill_qty);
            }

            if *trade_count < MAX_TRADES_PER_MATCH {
                trades[*trade_count] = Trade {
                    buyer: pool.data[bid_idx as usize].account_id,
                    seller: pool.data[incoming_idx as usize].account_id,
                    price: bid_price,
                    qty: fill_qty,
                    instrument_id,
                    timestamp: std::time::SystemTime::now()
                        .duration_since(std::time::UNIX_EPOCH)
                        .unwrap_or_default()
                        .as_nanos() as u64,
                };
                *trade_count += 1;
            }

            if pool.data[bid_idx as usize].remaining == 0 {
                book.remove_order(bid_idx, pool);
            }

            if *trade_count >= MAX_TRADES_PER_MATCH {
                break;
            }
        }
    }
}
