use crate::book::OrderBook;
use crate::constants::{MAX_INSTRUMENTS, MAX_TRADES_PER_MATCH};
use crate::instrument::{Instrument, InstrumentRegistry, SOVEREIGNS};
use crate::order::{ClientOrderId, ExchangeOrderId, OrderPacket};
use crate::pool::OrderPool;
use crate::sequence::SequenceNumber;

/// A trade generated by one instrument's matching engine.
///
/// Canonical sequence numbers identify the exchange admission order of both
/// participating orders. Client timestamps are retained only as metadata and
/// never participate in matching priority.
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct Trade {
    pub buyer: u32,
    pub seller: u32,
    pub price: u32,
    pub qty: u32,
    pub instrument_id: u16,
    pub buyer_exchange_order_id: u64,
    pub seller_exchange_order_id: u64,
    pub buyer_client_order_id: u64,
    pub seller_client_order_id: u64,
    pub buyer_sequence_number: u64,
    pub seller_sequence_number: u64,
    pub timestamp: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OrderAcceptError {
    InvalidInstrument(u16),
    InvalidSide(u8),
    DuplicateClientOrderId {
        instrument_id: u16,
        account_id: u32,
        client_order_id: ClientOrderId,
    },
    ExchangeOrderIdExhausted,
    SequenceNumberExhausted,
}

/// Handle returned when a packet is accepted into the matching engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AcceptedOrder {
    pub pool_index: u32,
    pub exchange_order_id: ExchangeOrderId,
    pub sequence_number: SequenceNumber,
}

/// Single-writer matching engine with one independent CLOB per instrument.
///
/// `next_sequence_number` is the canonical admission clock. Every accepted
/// command, including cancellation commands, receives exactly one sequence
/// number. Rejected commands consume neither an exchange order ID nor a
/// sequence number.
pub struct MatchingEngine {
    pub pool: OrderPool,
    pub books: Vec<OrderBook>,
    pub instruments: InstrumentRegistry,
    pub trades: [Trade; MAX_TRADES_PER_MATCH],
    pub trade_count: usize,
    next_exchange_order_id: u64,
    next_sequence_number: u64,
}

impl MatchingEngine {
    pub fn new() -> Self {
        Self {
            pool: OrderPool::new(),
            books: (0..MAX_INSTRUMENTS).map(|_| OrderBook::new()).collect(),
            instruments: InstrumentRegistry::from_sovereigns(SOVEREIGNS),
            trades: [Trade::default(); MAX_TRADES_PER_MATCH],
            trade_count: 0,
            next_exchange_order_id: 1,
            next_sequence_number: SequenceNumber::FIRST.0,
        }
    }

    #[inline(always)]
    pub fn instrument(&self, instrument_id: u16) -> Option<&Instrument> {
        self.instruments.get(instrument_id)
    }

    #[inline(always)]
    pub fn book(&self, instrument_id: u16) -> Option<&OrderBook> {
        self.books.get(instrument_id as usize)
    }

    #[inline(always)]
    pub fn book_mut(&mut self, instrument_id: u16) -> Option<&mut OrderBook> {
        self.books.get_mut(instrument_id as usize)
    }

    /// Validate and allocate a packet, assigning exchange identity and the
    /// canonical exchange sequence only after all admission checks succeed.
    ///
    /// The sequence is the ordering authority. The packet's client timestamp
    /// is metadata only and is never consulted for FIFO priority.
    #[inline]
    pub fn accept_order(&mut self, packet: &OrderPacket) -> Result<AcceptedOrder, OrderAcceptError> {
        if !self.instruments.contains(packet.instrument_id) {
            return Err(OrderAcceptError::InvalidInstrument(packet.instrument_id));
        }
        if packet.side > 2 {
            return Err(OrderAcceptError::InvalidSide(packet.side));
        }

        let client_order_id = packet.client_order_id();
        let book = &self.books[packet.instrument_id as usize];

        // Cancellation targets an existing client order and therefore does not
        // participate in duplicate-order admission.
        if packet.side != 2 && book.contains_order(packet.account_id, client_order_id) {
            return Err(OrderAcceptError::DuplicateClientOrderId {
                instrument_id: packet.instrument_id,
                account_id: packet.account_id,
                client_order_id,
            });
        }

        let sequence_number = self.next_sequence_number;
        let Some(next_sequence) = sequence_number.checked_add(1) else {
            return Err(OrderAcceptError::SequenceNumberExhausted);
        };

        let exchange_order_id = if packet.side == 2 {
            ExchangeOrderId(0)
        } else {
            let id = self.next_exchange_order_id;
            let Some(next) = id.checked_add(1) else {
                return Err(OrderAcceptError::ExchangeOrderIdExhausted);
            };
            self.next_exchange_order_id = next;
            ExchangeOrderId(id)
        };

        self.next_sequence_number = next_sequence;
        let pool_index = self
            .pool
            .allocate_from_packet(packet, exchange_order_id, SequenceNumber(sequence_number));

        Ok(AcceptedOrder {
            pool_index,
            exchange_order_id,
            sequence_number: SequenceNumber(sequence_number),
        })
    }

    /// Process an already sequenced command.
    ///
    /// The caller must deliver accepted commands to this single-writer matcher
    /// in ascending `sequence_number` order. This is the sequencer/matcher
    /// boundary: once admitted, sequence order is authoritative regardless of
    /// client timestamps, network arrival timestamps, or thread scheduling.
    #[inline(always)]
    pub fn process_order(&mut self, idx: u32) -> usize {
        self.trade_count = 0;

        let instrument_id = self.pool.data[idx as usize].instrument_id;
        let side = self.pool.data[idx as usize].side;

        if !self.instruments.contains(instrument_id) {
            self.pool.deallocate(idx);
            return 0;
        }

        if side == 2 {
            let account_id = self.pool.data[idx as usize].account_id;
            let client_order_id = ClientOrderId(self.pool.data[idx as usize].client_order_id);
            self.cancel_order(instrument_id, account_id, client_order_id);
            self.pool.deallocate(idx);
            return 0;
        }

        if side > 1 {
            self.pool.deallocate(idx);
            return 0;
        }

        let book = &mut self.books[instrument_id as usize];
        let pool = &mut self.pool;
        let trades = &mut self.trades;
        let trade_count = &mut self.trade_count;

        if side == 0 {
            Self::match_buy(pool, book, trades, trade_count, instrument_id, idx);
        } else {
            Self::match_sell(pool, book, trades, trade_count, instrument_id, idx);
        }

        if pool.data[idx as usize].remaining > 0 {
            book.insert_limit(idx, pool);
        } else {
            pool.deallocate(idx);
        }

        *trade_count
    }

    /// Cancel by the client identity within one instrument. Exchange order IDs
    /// are deliberately not accepted here: clients must not be able to cancel
    /// another account's order merely by learning its exchange ID.
    #[inline(always)]
    pub fn cancel_order(
        &mut self,
        instrument_id: u16,
        account_id: u32,
        client_order_id: ClientOrderId,
    ) -> bool {
        if !self.instruments.contains(instrument_id) {
            return false;
        }
        self.books[instrument_id as usize].cancel_order(
            account_id,
            client_order_id,
            &mut self.pool,
        )
    }

    #[inline(always)]
    pub fn remove_order_by_id(
        &mut self,
        instrument_id: u16,
        account_id: u32,
        client_order_id: ClientOrderId,
    ) -> bool {
        self.cancel_order(instrument_id, account_id, client_order_id)
    }

    #[inline(always)]
    fn match_buy(
        pool: &mut OrderPool,
        book: &mut OrderBook,
        trades: &mut [Trade; MAX_TRADES_PER_MATCH],
        trade_count: &mut usize,
        instrument_id: u16,
        incoming_idx: u32,
    ) {
        let incoming_price = pool.data[incoming_idx as usize].price;

        while pool.data[incoming_idx as usize].remaining > 0 {
            let Some(best_ask) = book.best_ask() else { break };
            if incoming_price < best_ask {
                break;
            }

            let Some(ask_idx) = book.best_ask_head() else { break };
            let ask_price = pool.data[ask_idx as usize].price;
            let ask_remaining = pool.data[ask_idx as usize].remaining;
            let incoming_remaining = pool.data[incoming_idx as usize].remaining;
            let fill_qty = incoming_remaining.min(ask_remaining);

            pool.data[incoming_idx as usize].remaining -= fill_qty;
            pool.data[ask_idx as usize].remaining -= fill_qty;

            if let Some(level) = book.asks.get_mut(&ask_price) {
                level.volume = level.volume.saturating_sub(fill_qty);
            }

            if *trade_count < MAX_TRADES_PER_MATCH {
                trades[*trade_count] = Trade {
                    buyer: pool.data[incoming_idx as usize].account_id,
                    seller: pool.data[ask_idx as usize].account_id,
                    price: ask_price,
                    qty: fill_qty,
                    instrument_id,
                    buyer_exchange_order_id: pool.data[incoming_idx as usize].exchange_order_id,
                    seller_exchange_order_id: pool.data[ask_idx as usize].exchange_order_id,
                    buyer_client_order_id: pool.data[incoming_idx as usize].client_order_id,
                    seller_client_order_id: pool.data[ask_idx as usize].client_order_id,
                    buyer_sequence_number: pool.data[incoming_idx as usize].sequence_number,
                    seller_sequence_number: pool.data[ask_idx as usize].sequence_number,
                    timestamp: std::time::SystemTime::now()
                        .duration_since(std::time::UNIX_EPOCH)
                        .unwrap_or_default()
                        .as_nanos() as u64,
                };
                *trade_count += 1;
            }

            if pool.data[ask_idx as usize].remaining == 0 {
                book.remove_order(ask_idx, pool);
            }

            if *trade_count >= MAX_TRADES_PER_MATCH {
                break;
            }
        }
    }

    #[inline(always)]
    fn match_sell(
        pool: &mut OrderPool,
        book: &mut OrderBook,
        trades: &mut [Trade; MAX_TRADES_PER_MATCH],
        trade_count: &mut usize,
        instrument_id: u16,
        incoming_idx: u32,
    ) {
        let incoming_price = pool.data[incoming_idx as usize].price;

        while pool.data[incoming_idx as usize].remaining > 0 {
            let Some(best_bid) = book.best_bid() else { break };
            if incoming_price > best_bid {
                break;
            }

            let Some(bid_idx) = book.best_bid_head() else { break };
            let bid_price = pool.data[bid_idx as usize].price;
            let bid_remaining = pool.data[bid_idx as usize].remaining;
            let incoming_remaining = pool.data[incoming_idx as usize].remaining;
            let fill_qty = incoming_remaining.min(bid_remaining);

            pool.data[incoming_idx as usize].remaining -= fill_qty;
            pool.data[bid_idx as usize].remaining -= fill_qty;

            if let Some(level) = book.bids.get_mut(&bid_price) {
                level.volume = level.volume.saturating_sub(fill_qty);
            }

            if *trade_count < MAX_TRADES_PER_MATCH {
                trades[*trade_count] = Trade {
                    buyer: pool.data[bid_idx as usize].account_id,
                    seller: pool.data[incoming_idx as usize].account_id,
                    price: bid_price,
                    qty: fill_qty,
                    instrument_id,
                    buyer_exchange_order_id: pool.data[bid_idx as usize].exchange_order_id,
                    seller_exchange_order_id: pool.data[incoming_idx as usize].exchange_order_id,
                    buyer_client_order_id: pool.data[bid_idx as usize].client_order_id,
                    seller_client_order_id: pool.data[incoming_idx as usize].client_order_id,
                    buyer_sequence_number: pool.data[bid_idx as usize].sequence_number,
                    seller_sequence_number: pool.data[incoming_idx as usize].sequence_number,
                    timestamp: std::time::SystemTime::now()
                        .duration_since(std::time::UNIX_EPOCH)
                        .unwrap_or_default()
                        .as_nanos() as u64,
                };
                *trade_count += 1;
            }

            if pool.data[bid_idx as usize].remaining == 0 {
                book.remove_order(bid_idx, pool);
            }

            if *trade_count >= MAX_TRADES_PER_MATCH {
                break;
            }
        }
    }
}
